// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"net/http"
	"sync"

	"github.com/concourse/atc/auth"
)

type FakeValidatingUserContextReader struct {
	IsAuthenticatedStub        func(*http.Request) bool
	isAuthenticatedMutex       sync.RWMutex
	isAuthenticatedArgsForCall []struct {
		arg1 *http.Request
	}
	isAuthenticatedReturns struct {
		result1 bool
	}
	isAuthenticatedReturnsOnCall map[int]struct {
		result1 bool
	}
	GetTeamStub        func(r *http.Request) (string, bool, bool)
	getTeamMutex       sync.RWMutex
	getTeamArgsForCall []struct {
		r *http.Request
	}
	getTeamReturns struct {
		result1 string
		result2 bool
		result3 bool
	}
	getTeamReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 bool
	}
	GetSystemStub        func(r *http.Request) (bool, bool)
	getSystemMutex       sync.RWMutex
	getSystemArgsForCall []struct {
		r *http.Request
	}
	getSystemReturns struct {
		result1 bool
		result2 bool
	}
	getSystemReturnsOnCall map[int]struct {
		result1 bool
		result2 bool
	}
	GetCSRFTokenStub        func(r *http.Request) (string, bool)
	getCSRFTokenMutex       sync.RWMutex
	getCSRFTokenArgsForCall []struct {
		r *http.Request
	}
	getCSRFTokenReturns struct {
		result1 string
		result2 bool
	}
	getCSRFTokenReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeValidatingUserContextReader) IsAuthenticated(arg1 *http.Request) bool {
	fake.isAuthenticatedMutex.Lock()
	ret, specificReturn := fake.isAuthenticatedReturnsOnCall[len(fake.isAuthenticatedArgsForCall)]
	fake.isAuthenticatedArgsForCall = append(fake.isAuthenticatedArgsForCall, struct {
		arg1 *http.Request
	}{arg1})
	fake.recordInvocation("IsAuthenticated", []interface{}{arg1})
	fake.isAuthenticatedMutex.Unlock()
	if fake.IsAuthenticatedStub != nil {
		return fake.IsAuthenticatedStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.isAuthenticatedReturns.result1
}

func (fake *FakeValidatingUserContextReader) IsAuthenticatedCallCount() int {
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	return len(fake.isAuthenticatedArgsForCall)
}

func (fake *FakeValidatingUserContextReader) IsAuthenticatedArgsForCall(i int) *http.Request {
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	return fake.isAuthenticatedArgsForCall[i].arg1
}

func (fake *FakeValidatingUserContextReader) IsAuthenticatedReturns(result1 bool) {
	fake.IsAuthenticatedStub = nil
	fake.isAuthenticatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeValidatingUserContextReader) IsAuthenticatedReturnsOnCall(i int, result1 bool) {
	fake.IsAuthenticatedStub = nil
	if fake.isAuthenticatedReturnsOnCall == nil {
		fake.isAuthenticatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isAuthenticatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeValidatingUserContextReader) GetTeam(r *http.Request) (string, bool, bool) {
	fake.getTeamMutex.Lock()
	ret, specificReturn := fake.getTeamReturnsOnCall[len(fake.getTeamArgsForCall)]
	fake.getTeamArgsForCall = append(fake.getTeamArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetTeam", []interface{}{r})
	fake.getTeamMutex.Unlock()
	if fake.GetTeamStub != nil {
		return fake.GetTeamStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.getTeamReturns.result1, fake.getTeamReturns.result2, fake.getTeamReturns.result3
}

func (fake *FakeValidatingUserContextReader) GetTeamCallCount() int {
	fake.getTeamMutex.RLock()
	defer fake.getTeamMutex.RUnlock()
	return len(fake.getTeamArgsForCall)
}

func (fake *FakeValidatingUserContextReader) GetTeamArgsForCall(i int) *http.Request {
	fake.getTeamMutex.RLock()
	defer fake.getTeamMutex.RUnlock()
	return fake.getTeamArgsForCall[i].r
}

func (fake *FakeValidatingUserContextReader) GetTeamReturns(result1 string, result2 bool, result3 bool) {
	fake.GetTeamStub = nil
	fake.getTeamReturns = struct {
		result1 string
		result2 bool
		result3 bool
	}{result1, result2, result3}
}

func (fake *FakeValidatingUserContextReader) GetTeamReturnsOnCall(i int, result1 string, result2 bool, result3 bool) {
	fake.GetTeamStub = nil
	if fake.getTeamReturnsOnCall == nil {
		fake.getTeamReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 bool
		})
	}
	fake.getTeamReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 bool
	}{result1, result2, result3}
}

func (fake *FakeValidatingUserContextReader) GetSystem(r *http.Request) (bool, bool) {
	fake.getSystemMutex.Lock()
	ret, specificReturn := fake.getSystemReturnsOnCall[len(fake.getSystemArgsForCall)]
	fake.getSystemArgsForCall = append(fake.getSystemArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetSystem", []interface{}{r})
	fake.getSystemMutex.Unlock()
	if fake.GetSystemStub != nil {
		return fake.GetSystemStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getSystemReturns.result1, fake.getSystemReturns.result2
}

func (fake *FakeValidatingUserContextReader) GetSystemCallCount() int {
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	return len(fake.getSystemArgsForCall)
}

func (fake *FakeValidatingUserContextReader) GetSystemArgsForCall(i int) *http.Request {
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	return fake.getSystemArgsForCall[i].r
}

func (fake *FakeValidatingUserContextReader) GetSystemReturns(result1 bool, result2 bool) {
	fake.GetSystemStub = nil
	fake.getSystemReturns = struct {
		result1 bool
		result2 bool
	}{result1, result2}
}

func (fake *FakeValidatingUserContextReader) GetSystemReturnsOnCall(i int, result1 bool, result2 bool) {
	fake.GetSystemStub = nil
	if fake.getSystemReturnsOnCall == nil {
		fake.getSystemReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 bool
		})
	}
	fake.getSystemReturnsOnCall[i] = struct {
		result1 bool
		result2 bool
	}{result1, result2}
}

func (fake *FakeValidatingUserContextReader) GetCSRFToken(r *http.Request) (string, bool) {
	fake.getCSRFTokenMutex.Lock()
	ret, specificReturn := fake.getCSRFTokenReturnsOnCall[len(fake.getCSRFTokenArgsForCall)]
	fake.getCSRFTokenArgsForCall = append(fake.getCSRFTokenArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetCSRFToken", []interface{}{r})
	fake.getCSRFTokenMutex.Unlock()
	if fake.GetCSRFTokenStub != nil {
		return fake.GetCSRFTokenStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getCSRFTokenReturns.result1, fake.getCSRFTokenReturns.result2
}

func (fake *FakeValidatingUserContextReader) GetCSRFTokenCallCount() int {
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	return len(fake.getCSRFTokenArgsForCall)
}

func (fake *FakeValidatingUserContextReader) GetCSRFTokenArgsForCall(i int) *http.Request {
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	return fake.getCSRFTokenArgsForCall[i].r
}

func (fake *FakeValidatingUserContextReader) GetCSRFTokenReturns(result1 string, result2 bool) {
	fake.GetCSRFTokenStub = nil
	fake.getCSRFTokenReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeValidatingUserContextReader) GetCSRFTokenReturnsOnCall(i int, result1 string, result2 bool) {
	fake.GetCSRFTokenStub = nil
	if fake.getCSRFTokenReturnsOnCall == nil {
		fake.getCSRFTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.getCSRFTokenReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeValidatingUserContextReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	fake.getTeamMutex.RLock()
	defer fake.getTeamMutex.RUnlock()
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeValidatingUserContextReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.ValidatingUserContextReader = new(FakeValidatingUserContextReader)
